[project]
name = "arpit-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "arpit sharma", email = "harsh941941@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
]

[project.scripts]
arpit-project = "arpit_project:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
