type User @table {
  username: String!
  email: String!
  profileImageUrl: String
  bio: String
}

type Artist @table {
  name: String!
  bio: String
  genre: String
  verifiedStatus: Boolean
}

type Song @table {
  title: String!
  duration: Int!
  releaseDate: Date
  albumName: String
  audioUrl: String
  artist: Artist!
}

type Playlist @table {
  title: String!
  description: String
  isPublic: Boolean
  user: User!
}

type PlaylistEntry @table {
  addedAt: Timestamp
  song: Song!
  playlist: Playlist!
}

type Favorite @table {
  timestamp: Timestamp
  user: User!
  song: Song!
}

type Follow @table {
  follower: User!
  following: User!
}